# Generated by Django 5.2.8 on 2025-11-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=100)),
                ('material', models.CharField(help_text='Enter the material of the product', max_length=100)),
                ('colour', models.CharField(help_text='Enter the colour of the product', max_length=50)),
                ('size', models.CharField(help_text='Enter the size of the product', max_length=20)),
            ],
        ),
    ]
